### ISSUE TITLE
Using ts utility type causes tsoa routes to hang

### ISSUE THREAD

**Issue by MitchellMonaghan** [lukeautry/tsoa#750]
```javascript
import {
  Body,
  Controller,
  Post,
  Route,
  SuccessResponse,
} from "tsoa";

import { UserCreateInput } from '@prisma/client'

type UserCreationParams = Omit<UserCreateInput,
  'id' |
  'createdAt' |
  'lastPasswordChange' |
  'lastLogin' |
  'confirmed' |
  'failedLoginAttempts' |
  'locked' |
  'banned'
>

type test = {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
}

@Route("users")
export class UsersController extends Controller {
  @SuccessResponse(201, "Created")
  @Post()
  public async createUser(@Body() requestBody: test): Promise<void> {
  }
}
```

In the following code if you use the test type as the route body parameter type tsoa routes command works, but if you use the UserCreationParams type the command hangs and never finishes. I think it has to do with the usage of the ts utility type Omit.

**Comment by MitchellMonaghan** [comment]
It seems if i define the UserCreationParams on a single line it works, but breaks when spread over multiple lines. I tested and ts compiles the project either way and I don't get any IDE or lint errors.

```javascript
type UserCreationParams = Omit<UserCreateInput, 'id' | 'createdAt' | 'lastPasswordChange' | 'lastLogin' | 'confirmed' | 'failedLoginAttempts' | 'locked' | 'banned'>
```

**Comment by WoH** [comment]
This should be fixed by now. I had a similar issue, which is no longer one.

**Comment by vincentvanderweele** [comment]
@WoH this still happens to me (tsoa 3.8.0). Reproducible case which hangs:

```
interface Foo {
  prop1: string;
  prop2: string;
  prop3: string;
  prop4: string;
  prop5: string;
  prop6: string;
  prop7: string;
}

// this is how prettier format this
interface Bar
  extends Partial<
    Pick<
      Foo,
      'prop1' | 'prop2' | 'prop3' | 'prop4' | 'prop5' | 'prop6' | 'prop7'
    >
  > {}
```

It can be worked around in some ways:

```
// Option 1: remove the line breaks in Pick
interface Bar
  extends Partial<
    Pick<Foo, 'prop1' | 'prop2' | 'prop3' | 'prop4' | 'prop5' | 'prop6' | 'prop7'>
  > {}

// Option 2: extract  the Pick to a separate type (compatible with prettier)
interface Bar extends Partial<BarData> {}
type BarData = Pick<
  Foo,
  'prop1' | 'prop2' | 'prop3' | 'prop4' | 'prop5' | 'prop6' | 'prop7'
>;
```

I'd happily help out debugging this but I have no idea where to even start looking. Do you have any pointers?

**Comment by WoH** [comment]
I'd probably try to write a test (fixture) adding this and debug the pre-test script when it runs the code through the type resolver and break on the reference type resolution.
